cli:
        - command: trimal
          name: trimAl
          url: http://www.atgc-montpellier.fr/erable/binaries.php
          version_arg: -h
        - command: gmsn.pl
          name: GeneMarkS (gmsn.pl)
          url: http://topaz.gatech.edu/GeneMark/license_download.cgi
          version_arg: --version
        - command: seqkit
          name: seqkit
          url: https://bioinf.shenwei.me/seqkit/download/
          version_arg: version
        - command: usearch
          name: usearch
          url: https://www.drive5.com/usearch/
          version_arg: --version
        - command: proteinortho
          name: proteinortho
          url: https://gitlab.com/paulklemm_PHD/proteinortho
          version_arg: --version
        - command: samtools
          name: mafft
          url: http://www.htslib.org/download/
          version_arg: --version
        - command: parallel
          name: GNU parallel
          url: https://www.gnu.org/software/parallel/
          version_arg: --version
r:
        - dplyr
        - tidyr
        - seqinr
        - phytools
        - ape
        - phangorn
        - treeio
